/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TypingTournament } from "./TypingTournament";
export * as factories from "./factories";
export { TypingTournament__factory } from "./factories/TypingTournament__factory";
