/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TypingTournamentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "declareWinner"
      | "enterTournament"
      | "entryFee"
      | "gameFinished"
      | "gamePools"
      | "getGamePool"
      | "getPlayerCount"
      | "hasPlayerPaid"
      | "isGameFinished"
      | "owner"
      | "playerCount"
      | "playerPaid"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PlayerEntered"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "declareWinner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enterTournament",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "entryFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "gameFinished",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gamePools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGamePool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPlayerPaid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isGameFinished",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerPaid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "declareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterTournament",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gameFinished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gamePools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGamePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPlayerPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGameFinished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playerPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEnteredEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TypingTournament extends BaseContract {
  connect(runner?: ContractRunner | null): TypingTournament;
  waitForDeployment(): Promise<this>;

  interface: TypingTournamentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  declareWinner: TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  enterTournament: TypedContractMethod<
    [gameId: BigNumberish],
    [void],
    "payable"
  >;

  entryFee: TypedContractMethod<[], [bigint], "view">;

  gameFinished: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  gamePools: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getGamePool: TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;

  getPlayerCount: TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;

  hasPlayerPaid: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;

  isGameFinished: TypedContractMethod<
    [gameId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  playerCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  playerPaid: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "declareWinner"
  ): TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterTournament"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "entryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gameFinished"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "gamePools"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGamePool"
  ): TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerCount"
  ): TypedContractMethod<[gameId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasPlayerPaid"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGameFinished"
  ): TypedContractMethod<[gameId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerPaid"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEntered"
  ): TypedContractEvent<
    PlayerEnteredEvent.InputTuple,
    PlayerEnteredEvent.OutputTuple,
    PlayerEnteredEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlayerEntered(uint256,address,uint256)": TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;
    PlayerEntered: TypedContractEvent<
      PlayerEnteredEvent.InputTuple,
      PlayerEnteredEvent.OutputTuple,
      PlayerEnteredEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
